# Generated from proto/full.proto. DO NOT EDIT.
# Generated by protoc-gen-py v0.2.0 with parameter "init_files=true".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Literal, TYPE_CHECKING, TypeAlias

from protobuf import Message
from protobuf._codegen import file_desc

if TYPE_CHECKING:
    from protobuf import DescFile


_StatusFields: TypeAlias = Literal["request_id", "code", "msg"]

class Status(Message[_StatusFields]):
    """
    ```proto
    message yh.Status
    ```

    Attributes:
        request_id:
            ```proto
            int64 request_id = 1;
            ```
        code:
            ```proto
            int32 code = 2;
            ```
        msg:
            ```proto
            string msg = 3;
            ```
    """

    __slots__ = ("request_id", "code", "msg")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            request_id: int = 0,
            code: int = 0,
            msg: str = "",
        ) -> None:
            pass

        request_id: int
        code: int
        msg: str

_GetUserRequestFields: TypeAlias = Literal["id"]

class GetUserRequest(Message[_GetUserRequestFields]):
    """
    ```proto
    message yh.GetUserRequest
    ```

    Attributes:
        id:
            ```proto
            string id = 2;
            ```
    """

    __slots__ = ("id",)

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            id: str = "",
        ) -> None:
            pass

        id: str

_GetUserResponseFields: TypeAlias = Literal["status", "data"]

class GetUserResponse(Message[_GetUserResponseFields]):
    """
    获取用户响应

    ```proto
    message yh.GetUserResponse
    ```

    Attributes:
        status:

            4402 该用户不存在
            7100 因违反相关规定，该用户被封禁

            ```proto
            optional yh.Status status = 1;
            ```
        data:
            数据

            ```proto
            optional yh.GetUserResponse.Data data = 2;
            ```
    """

    __slots__ = ("status", "data")

    if TYPE_CHECKING:

        def __init__(
            self,
            *,
            status: Status | None = None,
            data: GetUserResponse.Data | None = None,
        ) -> None:
            pass

        status: Status | None
        data: GetUserResponse.Data | None

    _DataFields: TypeAlias = Literal["ban_id", "ban_until_timestamp", "ban_reason"]

    class Data(Message[_DataFields]):
        """
        ```proto
        message yh.GetUserResponse.Data
        ```

        Attributes:
            ban_id:
                封禁 ID

                ```proto
                int64 ban_id = 9;
                ```
            ban_until_timestamp:
                封禁结束时间(时间戳),永久无此项

                ```proto
                int64 ban_until_timestamp = 10;
                ```
            ban_reason:
                封禁原因

                ```proto
                string ban_reason = 21;
                ```
        """

        __slots__ = ("ban_id", "ban_until_timestamp", "ban_reason")

        if TYPE_CHECKING:

            def __init__(
                self,
                *,
                ban_id: int = 0,
                ban_until_timestamp: int = 0,
                ban_reason: str = "",
            ) -> None:
                pass

            ban_id: int
            ban_until_timestamp: int
            ban_reason: str


_DESC = file_desc(
    b'\n\x10proto/full.proto\x12\x02yh"M\n\x06Status\x12\x1d\n\nrequest_id\x18\x01 \x01(\x03R\trequestId\x12\x12\n\x04code\x18\x02 \x01(\x05R\x04code\x12\x10\n\x03msg\x18\x03 \x01(\tR\x03msg" \n\x0eGetUserRequest\x12\x0e\n\x02id\x18\x02 \x01(\tR\x02id"\xd1\x01\n\x0fGetUserResponse\x12"\n\x06status\x18\x01 \x01(\x0b2\n.yh.StatusR\x06status\x12,\n\x04data\x18\x02 \x01(\x0b2\x18.yh.GetUserResponse.DataR\x04data\x1al\n\x04Data\x12\x15\n\x06ban_id\x18\t \x01(\x03R\x05banId\x12.\n\x13ban_until_timestamp\x18\n \x01(\x03R\x11banUntilTimestamp\x12\x1d\n\nban_reason\x18\x15 \x01(\tR\tbanReasonb\x06proto3',
    [],
    {
        "Status": Status,
        "GetUserRequest": GetUserRequest,
        "GetUserResponse": GetUserResponse,
        "GetUserResponse.Data": GetUserResponse.Data,
    },
)


def desc() -> DescFile:
    """Returns the descriptor for the file `proto/full.proto`."""
    return _DESC
